version: '3'

services:
  laser_alarm:
    image: zcking/hawkeye
    command: python hawkeye/laser_alarm.py
    container_name: laser-alarm
    env_file: .env
    restart: always
    privileged: true
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem"

